[package]
name = "capra"
version = "0.1.0"
authors = ["Anson <git@anson-cheung.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "capra"
path = "src/lib.rs"

[dependencies]
time = { version = "0.2.16", features = ["serde"] }
num-traits = "0.2.11"
thiserror = "1.0.19"
serde = { version = "1.0.110", optional = true, features = ["derive"]}

[features]
use-serde = ["serde"]