[package]
name = "capra"
version = "0.1.0"
authors = ["Anson <git@anson-cheung.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "capra"
path = "src/lib.rs"

[dependencies]
time = "0.2.16"
num-traits = "0.2.12"
thiserror = "1.0.20"
serde = { version = "1.0.114", optional = true}

[features]
use-serde = ["serde/derive", "time/serde"]